export { default as UsersPage } from './UsersPage'
export { default as SpotsPage } from './SpotsPage'
export { default as InteriorPage } from './InteriorPage'
export { default as SettingsPage } from './SettingsPage'
export { default as PageNotFound } from './PageNotFound'
